name: Sync, Build and Release

on:
  workflow_dispatch:  # Allow manual run
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  push:
    branches:
      - main  # Run if you push manually to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Important for git operations

    - name: Add upstream remote
      run: git remote add upstream https://github.com/anestisb/android-simg2img.git

    - name: Fetch and merge upstream
      run: |
        git fetch upstream
        git merge upstream/master --allow-unrelated-histories -m "Sync with upstream"

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libz-dev

    - name: Build project
      run: make

    - name: Make files executable
      run: |
        chmod +x append2simg img2simg simg2img simg2simg

    - name: Create archive
      run: tar czvf simg_tools.tar.gz append2simg img2simg simg2img simg2simg

    - name: Get date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"

    - name: Create tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag upstream-${{ steps.date.outputs.date }}
        git push origin upstream-${{ steps.date.outputs.date }}

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: simg_tools.tar.gz
        tag_name: upstream-${{ steps.date.outputs.date }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
