name: Sync, Build and Release

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC
  workflow_dispatch:     # Allow manual triggering
  push:
    branches:
      - main              # Also run on manual pushes to main

jobs:
  sync-build-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your fork
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # We need to set credentials manually to push

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add upstream and fetch
      run: |
        git remote add upstream https://github.com/anestisb/android-simg2img.git
        git fetch upstream
        git merge upstream/master --allow-unrelated-histories --no-edit || true
        git push origin main || true

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libz-dev

    - name: Build project
      run: make

    - name: Create tar.gz archive
      run: |
        tar czvf simg_tools.tar.gz append2simg img2simg simg2img simg2simg

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: simg_tools.tar.gz
        tag_name: nightly-${{ github.run_number }}
        name: Nightly Build ${{ github.run_number }}
        body: "Automatic nightly build syncing with upstream."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
